# Generated by Django 2.2.3 on 2019-07-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
