# Generated by Django 2.2.3 on 2019-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190805_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icons',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
